package br.com.ifba.giovaneneves.oopregistrationproject.view;

//--+ Imports +--//
import br.com.ifba.giovaneneves.oopregistrationproject.controller.FacadeInstance;
import br.com.ifba.giovaneneves.oopregistrationproject.exceptions.student.StudentNotFoundException;
import br.com.ifba.giovaneneves.oopregistrationproject.model.StudentsTableModel;
import br.com.ifba.giovaneneves.oopregistrationproject.model.Student;

import java.util.Collections;
import java.util.List;

import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
//--+ END Imports +--//
/**
 *
 * @author GiovaneNeves
 */
public class StudentDashboardGUI extends javax.swing.JFrame {
    //----------------------------------{ METHODS }----------------------------------//
    StudentsTableModel tableModel = new StudentsTableModel();

    //----------------------------------{ CONSTRUCTOR }----------------------------------//
    public StudentDashboardGUI() {

        initComponents();
        loadData();

        this.tblStudents.setModel(tableModel);
        tblStudents.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));

    }

    /**
     * Takes the data from the database and adds it to the table model.
     */
    private void loadData(){

        List<Student> students = FacadeInstance.getInstance().listAllStudents();

        Collections.sort(students, (student1, student2) -> student1.getName().compareTo(student2.getName()));

        if(!tableModel.getStudentList().isEmpty())
            tableModel.getStudentList().clear();

        tableModel.getStudentList().addAll(students);

        tableModel.fireTableDataChanged();
        loadDataLabels();
    }

    
    /**
     * Sets the values of the statistics labels.
     */
    public void loadDataLabels(){
    
        
        float sum = 0;
        for(int i = 0; i < tableModel.getStudentList().size(); i++)
            for(float grade : tableModel.getStudentList().get(i).getGrades())
                sum += grade;
        
        float average =  (sum / (tableModel.getStudentList().size() * 3));
        
        int totalApproved = 0;
        for(Student student  : tableModel.getStudentList()){
            if(student.getAverageGrades() > 7.0)
                totalApproved++;
        }
        
        this.lblNumberAverage.setText(String.valueOf(average));
        this.lblNumberTotalStudents.setText(String.valueOf(tableModel.getStudentList().size()));
        this.lblNumberApproved.setText(String.valueOf(totalApproved));
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBackground = new javax.swing.JPanel();
        jPnlBackgroundTopMenu = new javax.swing.JPanel();
        jPnlBackgroundOptionsMenu = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jBtnAddNewEntry = new javax.swing.JButton();
        lblDashboard = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        pnlAverage = new javax.swing.JPanel();
        lblAverage = new javax.swing.JLabel();
        lblNumberAverage = new javax.swing.JLabel();
        pnlApproved = new javax.swing.JPanel();
        lblApproved = new javax.swing.JLabel();
        lblNumberApproved = new javax.swing.JLabel();
        pnlSideMenuOptions = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jBtnMinimize = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();
        lblSideMenuOptions = new javax.swing.JLabel();
        pnlTotalStudents1 = new javax.swing.JPanel();
        lblTotalStudents = new javax.swing.JLabel();
        lblNumberTotalStudents = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBackground.setLayout(null);

        jPnlBackgroundTopMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBackgroundTopMenu.setLayout(null);

        jPnlBackgroundOptionsMenu.setBackground(new java.awt.Color(51, 51, 51));
        jPnlBackgroundOptionsMenu.setLayout(null);

        txtSearch.setText("Search");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        jPnlBackgroundOptionsMenu.add(txtSearch);
        txtSearch.setBounds(421, 9, 200, 30);

        jBtnAddNewEntry.setBackground(new java.awt.Color(0, 204, 102));
        jBtnAddNewEntry.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnAddNewEntry.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAddNewEntry.setText("ADD");
        jBtnAddNewEntry.setFocusPainted(false);
        jBtnAddNewEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddNewEntryActionPerformed(evt);
            }
        });
        jPnlBackgroundOptionsMenu.add(jBtnAddNewEntry);
        jBtnAddNewEntry.setBounds(350, 10, 60, 30);

        lblDashboard.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setText("DASHBOARD");
        jPnlBackgroundOptionsMenu.add(lblDashboard);
        lblDashboard.setBounds(10, 10, 140, 17);

        jPnlBackgroundTopMenu.add(jPnlBackgroundOptionsMenu);
        jPnlBackgroundOptionsMenu.setBounds(0, 0, 620, 40);

        jPnlBackground.add(jPnlBackgroundTopMenu);
        jPnlBackgroundTopMenu.setBounds(10, 0, 620, 40);

        tblStudents.setBackground(new java.awt.Color(51, 51, 51));
        tblStudents.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblStudents.setForeground(new java.awt.Color(255, 255, 255));
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        jPnlBackground.add(jScrollPane1);
        jScrollPane1.setBounds(100, 110, 530, 230);

        pnlAverage.setBackground(new java.awt.Color(0, 204, 102));

        lblAverage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAverage.setForeground(new java.awt.Color(255, 255, 255));
        lblAverage.setText("Average");

        lblNumberAverage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberAverage.setForeground(new java.awt.Color(255, 255, 255));
        lblNumberAverage.setText("0");

        javax.swing.GroupLayout pnlAverageLayout = new javax.swing.GroupLayout(pnlAverage);
        pnlAverage.setLayout(pnlAverageLayout);
        pnlAverageLayout.setHorizontalGroup(
            pnlAverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAverageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAverageLayout.createSequentialGroup()
                        .addComponent(lblAverage)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addComponent(lblNumberAverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlAverageLayout.setVerticalGroup(
            pnlAverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAverageLayout.createSequentialGroup()
                .addComponent(lblNumberAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lblAverage))
        );

        jPnlBackground.add(pnlAverage);
        pnlAverage.setBounds(310, 50, 70, 50);

        pnlApproved.setBackground(new java.awt.Color(0, 204, 102));

        lblApproved.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblApproved.setForeground(new java.awt.Color(255, 255, 255));
        lblApproved.setText("Approved");

        lblNumberApproved.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberApproved.setForeground(new java.awt.Color(255, 255, 255));
        lblNumberApproved.setText("0");

        javax.swing.GroupLayout pnlApprovedLayout = new javax.swing.GroupLayout(pnlApproved);
        pnlApproved.setLayout(pnlApprovedLayout);
        pnlApprovedLayout.setHorizontalGroup(
            pnlApprovedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlApprovedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlApprovedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberApproved, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlApprovedLayout.createSequentialGroup()
                        .addComponent(lblApproved)
                        .addContainerGap(9, Short.MAX_VALUE))))
        );
        pnlApprovedLayout.setVerticalGroup(
            pnlApprovedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlApprovedLayout.createSequentialGroup()
                .addComponent(lblNumberApproved, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(lblApproved))
        );

        jPnlBackground.add(pnlApproved);
        pnlApproved.setBounds(390, 50, 70, 50);

        pnlSideMenuOptions.setBackground(new java.awt.Color(51, 51, 51));

        btnEdit.setBackground(new java.awt.Color(0, 204, 102));
        btnEdit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhXFz84przDGqKoWKRMedu52xJTYnIHdvb3akNIRegHE8NiXK5B_1TZGkKFIO9JCfy8mJPNChY3s-CMflRGBieiZFDGgMAFuaQnMNeZ66jcujm7eZ7i40Fy1os6o5IzaO1JwDRBNuC5xwE3NN9IY8gFC2e_mcaqxNVMExuOdzqMJgGsOBlIjy2I54ld9A/s16/edit.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnEdit.setBorderPainted(false);
        btnEdit.setFocusPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEihC3843m67SQgMVXIJLcaDpi02CJswtTbS5ZD7X4afobE9-Gvj0a1vPkjH9Az428tTG2188FRIIYp99a4T3hfl8yiQVJZ7w-dRrJVOMo1pnkVDvLVYORuTnBAAfkNuXn5tLQ8RTGhWjDTV2TsxJlMdsnHRPUJd2Yd3ZmNZoQlf4TuAQK4d7XTaNDLQyQ/s16/trash-can.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnDelete.setBorderPainted(false);
        btnDelete.setFocusPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 204, 102));
        btnRefresh.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi6kvAMRmc2EoLE1bUda176Uzu45p4gMcy3YRy7jA48x8uq8pl4JKKE_DiETCYS80RiIr-MiR4nogvHoCddZiEBmFEU3120C5BwTD9f3zboGt379Bjfp7KmmDBRpyqqE03o5HDqCP15jJ4UKOcn5YExBXrmBqn5wByhguQB1UI-jhs-Nnvgr5ihhCn4GQ/s16/refresh.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jBtnMinimize.setBackground(new java.awt.Color(0, 204, 102));
        jBtnMinimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBtnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMinimize.setText("-");
        jBtnMinimize.setBorderPainted(false);
        jBtnMinimize.setFocusPainted(false);
        jBtnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinimizeActionPerformed(evt);
            }
        });

        jBtnClose.setBackground(new java.awt.Color(255, 0, 0));
        jBtnClose.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClose.setText("X");
        jBtnClose.setBorderPainted(false);
        jBtnClose.setFocusPainted(false);
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        lblSideMenuOptions.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSideMenuOptions.setForeground(new java.awt.Color(255, 255, 255));
        lblSideMenuOptions.setText("OPTIONS");

        javax.swing.GroupLayout pnlSideMenuOptionsLayout = new javax.swing.GroupLayout(pnlSideMenuOptions);
        pnlSideMenuOptions.setLayout(pnlSideMenuOptionsLayout);
        pnlSideMenuOptionsLayout.setHorizontalGroup(
            pnlSideMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideMenuOptionsLayout.createSequentialGroup()
                .addGroup(pnlSideMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlSideMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSideMenuOptionsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBtnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSideMenuOptionsLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pnlSideMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlSideMenuOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSideMenuOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSideMenuOptionsLayout.setVerticalGroup(
            pnlSideMenuOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideMenuOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSideMenuOptions)
                .addGap(14, 14, 14)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnMinimize)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPnlBackground.add(pnlSideMenuOptions);
        pnlSideMenuOptions.setBounds(10, 110, 80, 230);

        pnlTotalStudents1.setBackground(new java.awt.Color(0, 204, 102));
        pnlTotalStudents1.setForeground(new java.awt.Color(0, 204, 255));

        lblTotalStudents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalStudents.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalStudents.setText("Students");

        lblNumberTotalStudents.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberTotalStudents.setForeground(new java.awt.Color(255, 255, 255));
        lblNumberTotalStudents.setText("0");

        javax.swing.GroupLayout pnlTotalStudents1Layout = new javax.swing.GroupLayout(pnlTotalStudents1);
        pnlTotalStudents1.setLayout(pnlTotalStudents1Layout);
        pnlTotalStudents1Layout.setHorizontalGroup(
            pnlTotalStudents1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalStudents1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalStudents)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalStudents1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNumberTotalStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTotalStudents1Layout.setVerticalGroup(
            pnlTotalStudents1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalStudents1Layout.createSequentialGroup()
                .addComponent(lblNumberTotalStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalStudents))
        );

        jPnlBackground.add(pnlTotalStudents1);
        pnlTotalStudents1.setBounds(230, 50, 70, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(639, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinimizeActionPerformed
        
        //--+ Minimizes the window +--//
        setState(javax.swing.JFrame.ICONIFIED);
        
    }//GEN-LAST:event_jBtnMinimizeActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
       
        //--+ Closes the program +--//
        if(JOptionPane.showConfirmDialog(null, "Are you sure you want to close the program?", "Close Warning",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
        
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnAddNewEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddNewEntryActionPerformed
        
        new RegisterStudentGUI().setVisible(true);
    }//GEN-LAST:event_jBtnAddNewEntryActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        
        new StudentDashboardGUI().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * Deletes a student from the list
     */
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int id;

        if(tblStudents.getSelectedRow() == -1)
            id = Integer.parseInt(JOptionPane.showInputDialog(null, "Input the student ID", "Delete", JOptionPane.INFORMATION_MESSAGE));
        else
            id = tableModel.getStudentList().get(tblStudents.getSelectedRow()).getId();

        try{

            FacadeInstance.getInstance().removeStudent(id);
            loadData();

        } catch (StudentNotFoundException ex){

            JOptionPane.showMessageDialog(null, ex.getMessage(), "Delete", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();

        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        Student student = null;

        if(tblStudents.getSelectedRow() == -1){

            int id = Integer.parseInt(JOptionPane.showInputDialog(null, "Input the student ID", "Edit", JOptionPane.INFORMATION_MESSAGE));

            try{

                student = FacadeInstance.getInstance().findStudentById(id);

            } catch (StudentNotFoundException ex){

                JOptionPane.showMessageDialog(null, ex.getMessage(), "Edit", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();

            }

        }
        else
            student = tableModel.getStudentList().get(tblStudents.getSelectedRow());
        
        if(student != null){
            
            dispose();
            new EditStudentGUI(student).setVisible(true);
            
        } else
            JOptionPane.showMessageDialog(null, "Invalid student ID!", "Edit", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        
        searchByTypedText();
        
    }//GEN-LAST:event_txtSearchKeyTyped

    /**
     * Searches students based on text typed into the search bar.
     */
    public void searchByTypedText(){
        
        StudentsTableModel newTableModel = new StudentsTableModel();
        
        List<Student> students = FacadeInstance.getInstance().listAllStudents();
                
        //--+ Loads all data if the search field is empty +--//
        if(txtSearch.getText().isEmpty()){
            loadData();
            this.tblStudents.setModel(tableModel);
            return;
        }
        
        for(Student student : students){
            
            if(student.getName().contains(txtSearch.getText())){

                newTableModel.getStudentList().add(student);
                
            }
        }
        
        this.tblStudents.setModel(newTableModel);
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jBtnAddNewEntry;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnMinimize;
    private javax.swing.JPanel jPnlBackground;
    private javax.swing.JPanel jPnlBackgroundOptionsMenu;
    private javax.swing.JPanel jPnlBackgroundTopMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApproved;
    private javax.swing.JLabel lblAverage;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblNumberApproved;
    private javax.swing.JLabel lblNumberAverage;
    private javax.swing.JLabel lblNumberTotalStudents;
    private javax.swing.JLabel lblSideMenuOptions;
    private javax.swing.JLabel lblTotalStudents;
    private javax.swing.JPanel pnlApproved;
    private javax.swing.JPanel pnlAverage;
    private javax.swing.JPanel pnlSideMenuOptions;
    private javax.swing.JPanel pnlTotalStudents1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
