package com.github.nekoyasha7.oopregistrationproject.view;

import com.github.nekoyasha7.oopregistrationproject.model.StudentsTableModel;

import javax.swing.JOptionPane;

/**
 *
 * @author GiovaneNeves
 */
public class Students_GUI extends javax.swing.JFrame {

    StudentsTableModel tableModel = new StudentsTableModel();
    
    public Students_GUI() {
        initComponents();
    
        this.jTblStudents.setModel(tableModel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBackground = new javax.swing.JPanel();
        jPnlBackgroundTopMenu = new javax.swing.JPanel();
        jBtnMinimize = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();
        jPnlBackgroundOptionsMenu = new javax.swing.JPanel();
        jBtnAddNewEntry = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jBtnHomeScreen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblStudents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPnlBackground.setLayout(null);

        jPnlBackgroundTopMenu.setBackground(new java.awt.Color(204, 204, 204));
        jPnlBackgroundTopMenu.setLayout(null);

        jBtnMinimize.setText("-");
        jBtnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinimizeActionPerformed(evt);
            }
        });
        jPnlBackgroundTopMenu.add(jBtnMinimize);
        jBtnMinimize.setBounds(510, 10, 40, 22);

        jBtnClose.setText("X");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });
        jPnlBackgroundTopMenu.add(jBtnClose);
        jBtnClose.setBounds(560, 10, 50, 22);

        jPnlBackground.add(jPnlBackgroundTopMenu);
        jPnlBackgroundTopMenu.setBounds(10, 0, 620, 40);

        jPnlBackgroundOptionsMenu.setBackground(new java.awt.Color(153, 153, 153));
        jPnlBackgroundOptionsMenu.setLayout(null);

        jBtnAddNewEntry.setText("+");
        jBtnAddNewEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddNewEntryActionPerformed(evt);
            }
        });
        jPnlBackgroundOptionsMenu.add(jBtnAddNewEntry);
        jBtnAddNewEntry.setBounds(271, 6, 67, 28);

        jTextField1.setText("Pesquisar");
        jPnlBackgroundOptionsMenu.add(jTextField1);
        jTextField1.setBounds(21, 9, 150, 22);

        jBtnHomeScreen.setText("HOMESCREEN");
        jPnlBackgroundOptionsMenu.add(jBtnHomeScreen);
        jBtnHomeScreen.setBounds(435, 10, 140, 22);

        jPnlBackground.add(jPnlBackgroundOptionsMenu);
        jPnlBackgroundOptionsMenu.setBounds(10, 40, 620, 40);

        jTblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblStudents);

        jPnlBackground.add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 550, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(639, 372));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinimizeActionPerformed
        
        //--+ Minimizes the window +--//
        setState(javax.swing.JFrame.ICONIFIED);
        
    }//GEN-LAST:event_jBtnMinimizeActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
       
        //--+ Closes the program +--//
        if(JOptionPane.showConfirmDialog(null, "Are you sure you want to close the program?", "Close Warning",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            System.exit(0);
        
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnAddNewEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddNewEntryActionPerformed
        
        new AddStudent_GUI().setVisible(true);
    }//GEN-LAST:event_jBtnAddNewEntryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddNewEntry;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnHomeScreen;
    private javax.swing.JButton jBtnMinimize;
    private javax.swing.JPanel jPnlBackground;
    private javax.swing.JPanel jPnlBackgroundOptionsMenu;
    private javax.swing.JPanel jPnlBackgroundTopMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblStudents;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
